### PR TITLE
kvm: let clock scale setting apply immediately

### PR DESCRIPTION
**Pull request by vitalych**
Signed-off-by: Vitaly Chipounov <vitaly@cyberhaven.io>

### CODE REVIEW

**Comment by adrianherrera** [comment]
Can you mention in one of the commit messages why this change was made? I think it's good to note these things for future reference.

**Comment by vitalych** [comment]
@adrianherrera I mentioned it in the code. People don't really read commit messages.

**Comment by adrianherrera** [comment]
Hey, I read commit messages! :( Especially to see _why_ a change was made.

I was more after an explanation of why it was changed from an integer to a pointer. But sure, have at it.

**Review by adrianherrera — APPROVED** [review]

**Comment by vitalych** [comment]
Ok, good point, I will update the explanations

**Pull request merged**
